#!/usr/bin/env python
#sending mail to
import subprocess
import smtplib

threshold = 40
partition = "/"

def send_mail():
        SERVER = "localhost"
        FROM = "root"
        TO = ["Kannan.Vairamani@emeriocorp.com","Vajrala.Saisharma@emeriocorp.com","Bathina.Pullarao@emeriocorp.com"]
        SUBJECT = "Test Mail:Server running out of disk space"
        TEXT = "This message was sent from WEBAP53 server by using Python script."
        # Prepare actual message

        message = """\
        From: %s
        To: %s
        Subject: %s

        %s
        """ % (FROM, ", ".join(TO), SUBJECT, TEXT)

        # Send the mail

        server = smtplib.SMTP(SERVER)
        server.sendmail(FROM, TO, message)
        server.quit()
def check_disk():
        df = subprocess.Popen(["df","-h"], stdout=subprocess.PIPE)
        for line in df.stdout:
                splitline = line.decode().split()
                if splitline[5] == partition:
                        if int(splitline[4][:-1]) > threshold:
                                send_mail()
check_disk()
